spring:
  datasource:
    primary:
      driver-class-name:
      url:
      username:
      password:

# 雪花算法配置
snowflake:
  workerId: 1
  datacenterId: 1

# 日志配置
logging:
  file:
    path: /logs
  # 设置 Spring Boot 根日志级别为 INFO
  level:
    root: INFO