spring:
  datasource:
    dynamic:
      primary: primary
      datasource:
        primary:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url:
          username:
          password:
  redis:
    primary:
      host: 127.0.0.1
      port: 6379
      username:
      password:
      database: 0

# 雪花算法配置
snowflake:
  workerId: 1
  datacenterId: 1

# 日志配置
logging:
  file:
    path: /logs
  # 设置 Spring Boot 根日志级别为 INFO
  level:
    root: INFO
# AES秘钥存储路径
aes:
  keyPath: